project:
  type: website
  output-dir: docs

website:
  title: "UKCOTS"
  image: images/UKCOTS_24_500_white.png
  favicon: images/UKCOTS_24_500_white.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - ukcots25.qmd  
      - ukcots24.qmd
      - teachingstats.qmd
      - relatedevents.qmd
format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

resources:
  - CNAME

