---
title: "UKCOTS 25 - Delegate Information"
---

## **Getting to Glasgow**

**By air** - There are two main airports for domestic and international visitors to Glasgow:

- Glasgow Airport is roughly 15 minutes from the city centre with the [Airport Express 500](https://www.firstbus.co.uk/greater-glasgow/routes-and-maps/glasgow-airport-express) bus service available outside the terminal, with frequent services.

- Edinburgh Airport also has a [direct bus service](https://www.citylink.co.uk/timetables-service-updates/glasgow-edinburgh-airport/) to Glasgow City Centre which takes about an hour.

**By train** – Glasgow is well connected by train from across the UK by two main stations:

- Glasgow Central station links Glasgow to the south. 

- Glasgow Queen street operates routes mainly to Edinburgh and the north.

## **Getting to the UKCOTS venue**

UKCOTS will be held at the [Wolfson Medical School, University Avenue, Glasgow, G12 8QQ](https://frontdoor.spa.gla.ac.uk/map/embedded.html#!/?to=170) at the University of Glasgow’s West-End campus. You can access the building from University Avenue. [Citymapper](https://content.citymapper.com/news/2238/a-warm-welcome-to-edinburgh-and-glasgow) provides a detailed real-time route mapper, wherever you arrive initially in Glasgow.

To get to the venue from Glasgow City Centre, you can:

- Take the Subway to Hillhead on the Inner Circle. You can access the subway from the city centre at either the St Enoch or Buchannan Street stations. From Hillhead, it is a 3-minute walk to the Wolfson Medical School. The subway runs trains every 4 minutes at peak times, and 6-8 minutes at off peak times. To travel to Hillhead, take the **Inner Circle**. For return journeys to the city centre from Hillhead, take the **Outer Circle**. You will need to purchase a ticket prior to travelling at the station. Tickets are either single, return or all day (which provides unlimited travel for one day). Please keep hold of your ticket as you will need it to scan through barriers. More information on the subway can be found [here](https://www.spt.co.uk/travel-with-spt/subway/).

- Take a bus. The 4/4A service takes you from Hope Street to University Avenue, directly next to the Wolfson Medical School. The 4/4A run every 20 minutes. You can pay for the bus using your card for tap on-tap off or by cash. We would recommend using the [First Bus app](https://www.firstbus.co.uk/buy-tickets/ways-pay/first-bus-app) for live updates and planning your journey.

- By train. There are regular services (every 10 minutes roughly) between Glasgow Central and Glasgow Queen Street to Partick train station. The Wolfson Medical School is roughly a 15 minute walk from Partick train station.

- Take a Taxi (roughly around £10 – there is a taxi rank of black cabs outside Glasgow Central station). You can also book a taxi with Glasgow Taxis via their [app](https://www.glasgowtaxis.co.uk/download-app/). Uber is also available in Glasgow.

- Walk (about 40 minutes)

You can find a helpful map with hotel locations in the city to help plan your travel [here](supporting/hotelmap.pdf).

You can find further information on hotels around Glasgow and the university area [here](supporting/accommodation.pdf).

## **During the conference**

Most sessions and all refreshment breaks will be on the ground floor of the Wolfson Medical School. The registration desk will be in the foyer of the building. If you have any questions or concerns, please head to the registration desk which will be staffed through most of the conference. Members of the conference organising committee will be wearing a pink name badge.

Some sessions will be located in Room 745 on the seventh floor of the [James McCune Smith (JMS) building](https://frontdoor.spa.gla.ac.uk/map/embedded.html#!/?to=1730438AB). This building is directly across the road from the Wolfson Medical School.

Please note that at the conference there will be no welcome packs, no printed abstract booklets and no printed timetables. To help keep costs to a minimum, and to manage our environmental impact, we ask delegates to access all conference materials online.

## **Social Events**

Three social events (all within 5 mins walk from Buchanan St Subway in the City Centre) are planned:

-   Pre-conference social on Monday 23rd June, from 19:00, at [Shilling Brewing Co.](https://shillingbrewingcompany.co.uk/), 92 West George Street, Glasgow, G2 1PJ

-   **FREE** Civic drinks reception on Tuesday 24th June, 18:00-19:00, at [City Chambers](https://www.visitscotland.com/info/see-do/glasgow-city-chambers-p246401), 82 George Square, Glasgow, G2 1DU

-   **Not**-conference dinner on Tuesday 24th June, from 19:00, at [The Social](https://thesocialglasgow.co.uk/), 27 Royal Exchange Square, Glasgow, G1 3AJ. A limited menu will be available to order from (and pay!) at the bar or you can just come for the chat (and eat elsewhere).

There is no requirement to book any of the social events in advance, but it would be helpful if delegates complete the [UKCOTS25 social events](https://docs.google.com/forms/d/e/1FAIpQLSfO9RNE2SzRGtt_lEqYL277SbUDrvw5LxC1FuxiuNTzgYDknw/viewform) form so that we can advise the venues of likely numbers.

## **West-End coffee shops & breakfast options**

There are several local coffee shops and breakfast venues around the University on Byres Road, should you wish to grab a coffee at any point during the conference. A few of the places you can find are:

-   [Tinderbox](https://www.google.com/maps/place/Tinderbox/@55.8740081,-4.2956764,19z/data=!4m6!3m5!1s0x488845cfba109d79:0x99efb92fc8db847!8m2!3d55.873995!4d-4.295382!16s%2Fg%2F1tdqt379?entry=ttu&g_ep=EgoyMDI1MDYwMy4wIKXMDSoASAFQAw%3D%3D)
-   [Kember & Jones](https://www.google.com/maps/place/Kember+%26+Jones/@55.8740081,-4.2956764,19z/data=!4m6!3m5!1s0x488845cfb823de9b:0x5f6a25720d875ef7!8m2!3d55.8736844!4d-4.2952469!16s%2Fg%2F1ts3ksv4?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D)
-   [Level 11 Coffee Hub](https://www.google.com/maps/place/Level+11+coffee+hub/@55.8728186,-4.2974396,18.37z/data=!4m6!3m5!1s0x488845e71b822401:0x285265300e2e2b7d!8m2!3d55.8724403!4d-4.2971537!16s%2Fg%2F11vhd7107x?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D)
-   [Black Sheep Coffee](https://www.google.com/maps/place/Black+Sheep+Coffee/@55.875921,-4.2933486,20.11z/data=!3m1!5s0x488845ceef54616b:0x6f4656f6030303ba!4m6!3m5!1s0x488845e4ace7faf5:0x5f3cd75ddf19611a!8m2!3d55.8761514!4d-4.2929637!16s%2Fg%2F11ldq0hj_c?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D)
-   [Pret A Manger](https://www.google.com/maps/place/Pret+A+Manger/@55.8756283,-4.2933708,21z/data=!4m6!3m5!1s0x488845cef3d5c921:0xadef0758f57226cc!8m2!3d55.8755272!4d-4.2931142!16s%2Fg%2F11c2ldn1vw?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D)
-   [Starbucks](https://www.google.com/maps/place/Starbucks+Coffee/@55.8754368,-4.2938167,20.11z/data=!3m1!5s0x488845cef7a90a7b:0x28533ca4f9c40754!4m6!3m5!1s0x488845cef7293c8b:0x737e15c1b91e693e!8m2!3d55.8752851!4d-4.293291!16s%2Fg%2F1w6_ndhw?entry=ttu&g_ep=EgoyMDI1MDUyOC4wIKXMDSoASAFQAw%3D%3D)
-   [Greggs](https://www.google.com/maps/place/Greggs/@55.8766366,-4.2928943,19.75z/data=!3m1!5s0x488845cef7a90a7b:0x28533ca4f9c40754!4m6!3m5!1s0x488845000f7f96b3:0x309906f47cce93d4!8m2!3d55.8765929!4d-4.2925159!16s%2Fg%2F11w4bwk_c_?entry=tts&g_ep=EgoyMDI1MDUyOC4wIPu8ASoASAFQAw%3D%3D&skid=e4415b69-6ef1-48ab-8ffc-73773566eec8)

## **Delegate Offers**

The Glasgow Convention Bureau have kindly offered exclusive delegate offers for UKCOTS attendees for your visit to Glasgow. These contain various discounts on travel, dining and excursions if you plan on staying for a few extra days. A link to these offers can be found [here](https://www.visitglasgow.org.uk/convention-bureau/meeting-planners/delegate-offers/).
