---
title: "Related Events"
---

**Other conferences and events of interest**

- [CETL-MSOR](https://www.cetl-msor2024.com/){target="_blank"}, 29-30^th^ August 2024, at University of Limerick, Ireland.

- [Royal Statistical Society Conference](https://rss.org.uk/training-events/conference-2024/){target="_blank"}, 2-5^th^ September 2024, Brighton.

- [Higher Education Teaching and Learning Workshop Series](https://ima.org.uk/23689/higher-education-teaching-and-learning-workshop-series-2023-24-successful-proposals/){target="_blank"} (IMA, LMS and RSS funded), various dates and locations.

- [Burwalls](https://sites.google.com/view/burwalls/home){target="_blank"} 2025, dates and location TBA.

- [USCOTS](https://www.causeweb.org/cause/uscots/uscots25){target="_blank"}, 17-19^th^ July **2025**, Iowa.

- [RoSE network](https://www.rose-network.org/){target="_blank"} conference, 31^st^ July **2025**, online.

- [World Statistics Congress](https://www.isi-next.org/conferences/isi-wsc2025/){target="_blank"}, 5-9^th^ October **2025**, The Hague.

- [International Association for Statistical Education](http://iase-web.org/Conferences.php){target="_blank"}, various conferences including:

    - [International Conference on Teaching Statistics](http://iase-web.org/Conferences.php){target="_blank"}, 12-17^th^ July **2026**, Brisbane.

    - Satellite conference, 1-3^rd^ October 2025 in Munster, Germany (no website as yet).

- [International Association for Statistical Education](http://iase-web.org/Webinars.php){target="_blank"} webinars (including recordings of previous events), various dates.
