---
title: "UKCOTS 24"
---

**Outputs from UKCOTS 2024**

The first *UK Conference on Teaching Statistics* (UKCOTS) was organized by the [RSS Teaching Statistics Section](https://rss.org.uk/membership/rss-groups-and-committees/sections/teaching-statistics/) and held at the University of Manchester on the 13th and 14th of June, 2024. The 2024 UKCOTS conference also hosted the *Annual Conference for Teachers of Statistics in Medicine and Allied Health Sciences* (known as [*Burwalls*](https://sites.google.com/view/burwalls/home)).

**Slides from UKCOTS 2024**

Material from presenters who consented to sharing their slides can be accessed [here](https://github.com/rssteachingstats/UKCOTS-2024-Presentations). These are organised by day and parallel session. We encourage you to make contact with presenters directly if you are interested in their work, especially if their slides are not available here.

**Photos from UKCOTS 2024**

Photos from the conference can be found on the [UKCOTS Flickr site](https://www.flickr.com/photos/200955403@N03/albums/with/72177720318468484). Pictures from [pleneries, workshops and short oral sessions](https://www.flickr.com/photos/200955403@N03/albums/72177720318468484) and pictures from [refreshment breaks and the non-conference dinner](https://www.flickr.com/photos/200955403@N03/albums/72177720318448170/).

**Marking the first UKCOTS with a special edition of the journal *Teaching Statistics***

To mark the first UKCOTS, there will be a special edition of the journal [Teaching Statistics](https://onlinelibrary.wiley.com/journal/14679639). Delegates who presented at UKCOTS are encouraged to submit a paper for this special edition. See [here](special_edition.html) for more information.
