---
title: "UKCOTS 25 - Conference Information"
---

## **UKCOTS 2025 Timetable**

UKCOTS 2025 will take place on the **24th - 25th June** **at the [Wolfson Medical School](https://www.gla.ac.uk/myglasgow/estates/timetabling/roomphotos/wolfsonmed/), University of Glasgow**.

An outline schedule of events during the conference is now available to view [here](supporting/outlineschedule.pdf). A more detailed timetable of sessions will follow shortly.

## **Plenary Session - Generative AI vs. Critical Thinking**

We are delighted to announce that our plenary session at UKCOTS 2025 will explore the relationship between generative AI and critical thinking, studying its implications for higher education. Our three invited speakers will present perspectives on generative AI in education within their own practice, followed by a panel discussion.

[**Dr Emily Nordmann**](https://www.gla.ac.uk/schools/psychologyneuroscience/staff/emilynordmann/)

Dr Emily Nordmann is the Deputy Director of Education in the School of Psychology and Neuroscience and incoming Associate Dean for Learning and Teaching for the College of MVLS at the University of Glasgow. She specialises in the teaching and research of data skills using R, with a particular focus on making these skills accessible to undergraduate psychology students. Dr Nordmann is a core member of the *PsyTeachR* team, through which she has co-authored several open-access textbooks that promote data literacy. These resources are widely adopted across the UK and internationally, and have played a significant role in shaping best practice in statistics education within psychology.

[**Dr Jenn Gaskell**](https://www.gla.ac.uk/schools/mathematicsstatistics/staff/jennifergaskell/#)

Dr Jenn Gaskell is a Lecturer in the School of Maths & Stats at the University of Glasgow. Here, she chairs the school’s AI committee and is involved in the creation of several courses around effective and responsible AI usage for data scientists in both academia and industry. She teaches Python programming and machine-learning across the Statistics and Data Analytics Masters programmes. Jenn is interested in the impact of AI on statistical education, with a passion for teaching relevant skills for entering an AI-enabled workplace. 

## Social Events

During the conference, we will hold several social events including an informal dinner. All events will take place in the city centre of Glasgow. More details to follow.

## Accommodation for UKCOTS

Due to other events taking place in Glasgow around the time of UKCOTS, accommodation prices are likely to increase as we approach the conference date. We would encourage attendees of UKCOTS to book their accommodation early to avoid any price increases.

You can find further information on hotels around Glasgow and the university area [here](supporting/accommodation.pdf).

A map of hotels within Glasgow can also be found [here](supporting/hotelmap.pdf) to help with your planning.
